export const ICMPv4: string[] = [
  "ICMPv4 Type 0",
  "ICMPv4 Type 3",
  "ICMPv4 Type 5",
  "ICMPv4 Type 8",
  "ICMPv4 Type 9",
  "ICMPv4 Type 10",
  "ICMPv4 Type 11",
  "ICMPv4 Type 12",
  "ICMPv4 Type 13",
  "ICMPv4 Type 14",
  "ICMPv4 Type 40",
  "ICMPv4 Type 41",
  "ICMPv4 Type 42",
  "ICMPv4 Type 43",
  "ICMPv4 Type 253",
  "ICMPv4 Type 254",
];

export const ICMPv4_tooltips: string[] = [
  "Echo Reply",
  "Destination Unreachable",
  "Redirect",
  "Echo",
  "Router Advertisement",
  "Router Selection",
  "Time Exceeded",
  "Parameter Problem",
  "Timestamp",
  "Timestamp Reply",
  "Photuris",
  "ICMP messages utilized by experimental mobility protocols such as Seamoby",
  "Extended Echo Request",
  "Extended Echo Reply",
  "RFC3692-style Experiment 1",
  "RFC3692-style Experiment 2",
];

export const ICMPv6: string[] = [
  "ICMPv6 Type 1",
  "ICMPv6 Type 2",
  "ICMPv6 Type 3",
  "ICMPv6 Type 4",
  "ICMPv6 Type 128",
  "ICMPv6 Type 129",
  "ICMPv6 Type 130",
  "ICMPv6 Type 131",
  "ICMPv6 Type 132",
  "ICMPv6 Type 133",
  "ICMPv6 Type 134",
  "ICMPv6 Type 135",
  "ICMPv6 Type 136",
  "ICMPv6 Type 137",
  "ICMPv6 Type 138",
  "ICMPv6 Type 139",
  "ICMPv6 Type 140",
  "ICMPv6 Type 141",
  "ICMPv6 Type 142",
  "ICMPv6 Type 144",
  "ICMPv6 Type 145",
  "ICMPv6 Type 146",
  "ICMPv6 Type 147",
  "ICMPv6 Type 157",
  "ICMPv6 Type 158",
  "ICMPv6 Type 160",
  "ICMPv6 Type 161",
];

export const ICMPv6_tooltips: string[] = [
  "Destination Unreachable",
  "Packet Too Big",
  "Time Exceeded",
  "Parameter Problem",
  "Echo Request",
  "Echo Reply",
  "Multicast Listener Query",
  "Multicast Listener Report",
  "Multicast Listener Done",
  "Router Solicitation",
  "Router Advertisement",
  "Neighbor Solicitation",
  "Neighbor Advertisement",
  "Redirect Message",
  "Router Renumbering",
  "ICMP Node Information Query",
  "ICMP Node Information Response",
  "Inverse Neighbor Discovery",
  "Inverse Neighbor Discovery",
  "Home Agent Address Discovery",
  "Home Agent Address Discovery",
  "Mobile Prefix Solicitation",
  "Mobile Prefix Advertisement",
  "Duplicate Address Request Code Suffix",
  "Duplicate Address Confirmation Code Suffix",
  "Extended Echo Request",
  "Extended Echo Reply",
];
